---
# We don't really want to version real credentials or more sensitive config.
# This file can be used to easily tweak these sensitive settings by passing it
# as an extra-vars file like so:
# ansible-playbook -i hosts -e @config.yml playbooks/bootstrap_monitoring.yml
# The config.yml file is gitignored and can be used safely.

# rdomonitoring
monitoring_master_host: 'master.monitoring.rdoproject.org'
monitoring_rabbitmq_host: "{{ master_host }}"
monitoring_api_host: 'api.monitoring.rdoproject.org'
monitoring_uchiwa_host: 'uchiwa.monitoring.rdoproject.org'
monitoring_bot_host: 'bot.monitoring.rdoproject.org'
monitoring_rabbitmq_username:
monitoring_rabbitmq_password:
monitoring_rabbitmq_erlang_cookie:
monitoring_sensu_username:
monitoring_sensu_password:
monitoring_uchiwa_users: |
  uchiwa::users:
    - username: 'rdo'
      password: 'rdo'
      readonly: 'true'

# rdobot
rdobot_nickserv_password:
rdobot_sensu_password: "{{ monitoring_sensu_password }}"
